import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [15]:
###### tensor

In [4]:
x_ones=torch.ones_like(x_data)
print(f"ones tensor: \n{x_ones} \n")

ones tensor: 
tensor([[1, 1],
        [1, 1]]) 



In [5]:
x_rand=torch.rand_like(x_data, dtype=torch.float)
print(f"random tensor: \n {x_rand} \n")

random tensor: 
 tensor([[0.9311, 0.0414],
        [0.3562, 0.3694]]) 



In [6]:
## tensor -> numpy

In [7]:
t=torch.ones(5)
print(f"t: {t}")

t: tensor([1., 1., 1., 1., 1.])


In [8]:
n=t.numpy()
print(f"n:{n}")

n:[1. 1. 1. 1. 1.]


In [14]:
t.add_(1)
print(f"{t}")
print(f"{n}")

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
## numpy -> tensor

In [17]:
n=np.ones(5)
t=torch.from_numpy(n)

In [19]:
np.add(n,1,out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [ ]:
###### 연산 1

In [20]:
x = torch.tensor([1, 2, 3])
print(f"{x}")

tensor([1, 2, 3])


In [21]:
x = torch.zeros(3, 4) 
print(f"{x}")

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [22]:
x = torch.randn(3, 4)
print(f"{x}")

tensor([[-0.9101,  0.5672,  0.0307,  0.1607],
        [ 1.7905, -1.1602, -0.0295,  1.6033],
        [ 1.0916, -1.6349,  0.5617, -0.4377]])


In [23]:
x = torch.ones(2, 3, dtype=torch.float32)
print(f"{x}")

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
###### 연산 2

In [26]:
a = torch.randn(3, 4)
b = torch.randn(3, 4)
print(f"a: {a}")
print(f"b: {b}")

a: tensor([[ 0.9145,  0.3926,  0.3580,  1.5413],
        [-0.6023, -0.0629,  0.2825,  0.8376],
        [-1.0904,  0.9627,  1.0586, -1.1337]])
b: tensor([[ 0.5480,  0.8828,  1.4401, -0.1898],
        [ 0.5068, -0.2692, -1.2359, -0.4149],
        [ 1.2839, -0.9538,  0.9537,  1.0068]])


In [29]:
c = a + b            # 덧셈
d = a @ b.T          # 행렬곱 (matmul)
e = a * b            # 원소별 곱 
print(f"c: {c}\n")
print(f"d: {d}\n")
print(f"e: {e}")

c: tensor([[ 1.4625,  1.2755,  1.7981,  1.3515],
        [-0.0955, -0.3321, -0.9533,  0.4226],
        [ 0.1935,  0.0089,  2.0123, -0.1268]])

d: tensor([[ 1.0709, -0.7242,  2.6929],
        [-0.1377, -0.9850,  0.3995],
        [ 1.9920, -1.6496, -2.4501]])

e: tensor([[ 0.5012,  0.3466,  0.5156, -0.2925],
        [-0.3052,  0.0169, -0.3492, -0.3475],
        [-1.4000, -0.9183,  1.0096, -1.1415]])


In [ ]:
###### 연산 3

In [32]:
x=torch.randn(2, 3, 4)
print(f"x:{x}\n")
y=x.view(6,4)
print(f"y:{y}\n")
z=x.permute(0,2,1)
print(f"z:{z}")

x:tensor([[[-0.7194,  1.0986, -0.9109, -0.7726],
         [-1.1447, -0.0032,  0.3246, -0.3967],
         [ 0.0141, -0.5018, -0.1282, -1.6570]],

        [[ 0.8554,  0.2855,  2.3705,  2.8527],
         [-1.1371,  0.6606, -0.5318, -0.7216],
         [ 1.8897,  1.5112, -0.5607,  0.8365]]])

y:tensor([[-0.7194,  1.0986, -0.9109, -0.7726],
        [-1.1447, -0.0032,  0.3246, -0.3967],
        [ 0.0141, -0.5018, -0.1282, -1.6570],
        [ 0.8554,  0.2855,  2.3705,  2.8527],
        [-1.1371,  0.6606, -0.5318, -0.7216],
        [ 1.8897,  1.5112, -0.5607,  0.8365]])

z:tensor([[[-0.7194, -1.1447,  0.0141],
         [ 1.0986, -0.0032, -0.5018],
         [-0.9109,  0.3246, -0.1282],
         [-0.7726, -0.3967, -1.6570]],

        [[ 0.8554, -1.1371,  1.8897],
         [ 0.2855,  0.6606,  1.5112],
         [ 2.3705, -0.5318, -0.5607],
         [ 2.8527, -0.7216,  0.8365]]])
